version: "3"

services:
  mc_server:
    container_name: mc_server
    build:
      context: .
      dockerfile: ./minecraft/Dockerfile
    volumes:
      - ./minecraft:/workspace
    restart: always
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
