version: "3"

services:
  mc_server:
    container_name: mc_server
    build:
      context: .
      dockerfile: ./minecraft/Dockerfile
    networks:
      - server-net
    volumes:
      - .:/app
  agent:
    container_name: agent
    build:
      context: .
      dockerfile: ./agent/Dockerfile
    networks:
      - server-net
    volumes:
      - ./agent:/workspace
  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    volumes:
      - ./dashboard:/workspace

networks:
  server-net:
    driver: bridge
