version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: bundle exec rackup config.ru -p 4567 -o 0.0.0.0
    env_file: ./api/.env
    volumes:
      - ./api:/app
      - ./minecraft:/app/minecraft
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-compose.yml:/app/docker-compose.yml
    ports:
      - 4567:4567
    networks:
      - meps-net
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    command: bundle exec clockwork cron_worker.rb
    env_file:
      - ./worker/.env
    volumes:
      - ./worker:/app
      - ./backup:/app/backup
      - ./minecraft:/app/minecraft
    networks:
      - meps-net
  discordbot:
    build:
      context: .
      dockerfile: ./discordbot/Dockerfile
    command: bundle exec ruby discordbot.rb
    env_file:
      - ./discordbot/.env
    volumes:
      - ./discordbot:/app
    networks:
      - meps-net
  fluentd:
    build:
      context: .
      dockerfile: ./fluentd/Dockerfile
    command: bundle exec fluentd -c ./fluent.conf
    env_file: ./fluentd/.env
    volumes:
      - ./fluentd:/app
      - ./minecraft:/app/minecraft
      - ./api:/app/api
    networks:
      - meps-net
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    env_file: ./api/.env
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/migration:/docker-entrypoint-initdb.d
    networks:
      - meps-net
  mc_server:
    container_name: mc_server
    build:
      context: .
      dockerfile: ./minecraft/Dockerfile
    volumes:
      - ./minecraft:/workspace
    restart: always
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    networks:
      - meps-net
networks:
  meps-net:
    driver: bridge
