version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:4567
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
  mc_server:
    container_name: mc_server
    build:
      context: .
      dockerfile: ./minecraft/Dockerfile
    volumes:
      - ./minecraft:/workspace
    restart: always
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
