version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: bundle exec ruby server.rb -e production -p 4567
    env_file: ./api/.env
    volumes:
      - ./api:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 4567:4567
    networks:
      - msns-net
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    command: bundle exec clockwork cron_worker.rb
    env_file:
      - ./worker/.env
    volumes:
      - ./worker:/app
      - ./backup:/app/backup
      - ./minecraft:/app/minecraft
    networks:
      - msns-net
  fluentd:
    build:
      context: .
      dockerfile: ./docker/fluentd/Dockerfile
    command: bundle exec fluentd -c ./fluent.conf
    env_file: ./fluentd/.env
    volumes:
      - ./fluentd:/app
      - ./minecraft:/app/minecraft
      - ./api:/app/api
    networks:
      - msns-net
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    env_file: ./api/.env
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/migration:/docker-entrypoint-initdb.d
    networks:
      - msns-net
  mc_server:
    container_name: mc_server
    build:
      context: .
      dockerfile: ./docker/minecraft/Dockerfile
    volumes:
      - ./minecraft:/workspace
    restart: always
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    networks:
      - msns-net
networks:
  msns-net:
    driver: bridge
