version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - ${PORT}:4567
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - msns-net
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    env_file: .env
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/migration:/app
    networks:
      - msns-net
  mc_server:
    container_name: mc_server
    build:
      context: .
      dockerfile: ./docker/minecraft/Dockerfile
    volumes:
      - ./minecraft:/workspace
    restart: always
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    networks:
      - msns-net
networks:
  msns-net:
    driver: bridge
