# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv'
gem 'rubyzip'
gem 'logger'
gem 'rspec'
gem 'rest-client'
gem 'pry'
gem 'discordrb'
